/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dms.panels;

import dms.util.AccountingUtil;

/**
 *
 * @author Lester
 */
public class OldPanels extends javax.swing.JPanel {
	
	
	private String[] sql = null;

	/**
	 * Creates new form OldPanels
	 */
	public OldPanels() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel91 = new javax.swing.JPanel();
                jPanel105 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
                gpAccountField = new com.jidesoft.swing.AutoCompletionComboBox();
                jFormattedTextField2 = new javax.swing.JFormattedTextField();
                jFormattedTextField4 = new javax.swing.JFormattedTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField8 = new javax.swing.JTextField();
                jDateChooser3 = new com.toedter.calendar.JDateChooser();
                jButton2 = new javax.swing.JButton();
                jPanel106 = new javax.swing.JPanel();
                jLabel17 = new javax.swing.JLabel();
                jScrollPane22 = new javax.swing.JScrollPane();
                jTable6 = new javax.swing.JTable();

                setName("Form"); // NOI18N
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                jTabbedPane1.setName("jTabbedPane1"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dms.DMSApp.class).getContext().getResourceMap(OldPanels.class);
                jPanel91.setBackground(resourceMap.getColor("jPanel91.background")); // NOI18N
                jPanel91.setName("jPanel91"); // NOI18N
                jPanel91.setLayout(new java.awt.BorderLayout(0, 10));

                jPanel105.setName("jPanel105"); // NOI18N
                jPanel105.setOpaque(false);
                jPanel105.setLayout(new java.awt.GridLayout(2, 7, 10, 0));

                jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
                jLabel1.setName("jLabel1"); // NOI18N
                jPanel105.add(jLabel1);

                jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
                jLabel2.setName("jLabel2"); // NOI18N
                jPanel105.add(jLabel2);

                jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
                jLabel15.setName("jLabel15"); // NOI18N
                jPanel105.add(jLabel15);

                jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
                jLabel3.setName("jLabel3"); // NOI18N
                jPanel105.add(jLabel3);

                jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
                jLabel5.setName("jLabel5"); // NOI18N
                jPanel105.add(jLabel5);

                jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
                jLabel7.setName("jLabel7"); // NOI18N
                jPanel105.add(jLabel7);

                filler3.setName("filler3"); // NOI18N
                jPanel105.add(filler3);

                gpAccountField.setName("gpAccountField"); // NOI18N
                jPanel105.add(gpAccountField);

                jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
                jFormattedTextField2.setName("jFormattedTextField2"); // NOI18N
                jFormattedTextField2.setValue(0.00);
                jFormattedTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jFormattedTextField2debitAndCreditFocusLost(evt);
                        }
                });
                jPanel105.add(jFormattedTextField2);

                jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
                jFormattedTextField4.setName("jFormattedTextField4"); // NOI18N
                jFormattedTextField4.setValue(0.00);
                jPanel105.add(jFormattedTextField4);

                jTextField3.setName("jTextField3"); // NOI18N
                jPanel105.add(jTextField3);

                jTextField8.setName("jTextField8"); // NOI18N
                jPanel105.add(jTextField8);

                jDateChooser3.setDateFormatString(resourceMap.getString("jDateChooser3.dateFormatString")); // NOI18N
                jDateChooser3.setName("jDateChooser3"); // NOI18N
                jPanel105.add(jDateChooser3);

                jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
                jButton2.setName("jButton2"); // NOI18N
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2postButtonAction(evt);
                        }
                });
                jPanel105.add(jButton2);

                jPanel91.add(jPanel105, java.awt.BorderLayout.NORTH);

                jPanel106.setName("jPanel106"); // NOI18N
                jPanel106.setOpaque(false);
                jPanel106.setPreferredSize(new java.awt.Dimension(452, 200));
                jPanel106.setLayout(new java.awt.BorderLayout(0, 5));

                jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
                jLabel17.setName("jLabel17"); // NOI18N
                jPanel106.add(jLabel17, java.awt.BorderLayout.NORTH);

                jScrollPane22.setName("jScrollPane22"); // NOI18N

                jTable6.setAutoCreateRowSorter(true);
                jTable6.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Account", "Debit", "Credit", "Control", "Reference", "Date"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jTable6.setFillsViewportHeight(true);
                jTable6.setName("jTable6"); // NOI18N
                jTable6.getTableHeader().setReorderingAllowed(false);
                jScrollPane22.setViewportView(jTable6);

                jPanel106.add(jScrollPane22, java.awt.BorderLayout.CENTER);

                jPanel91.add(jPanel106, java.awt.BorderLayout.CENTER);

                jTabbedPane1.addTab("General Posting", jPanel91);

                add(jTabbedPane1);
        }// </editor-fold>//GEN-END:initComponents

        private void jFormattedTextField2debitAndCreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField2debitAndCreditFocusLost

		/*                
		if ((JFormattedTextField) evt.getSource() == jFormattedTextField2) {
                        if (((Number) jFormattedTextField2.getValue()).doubleValue() < 0.00) {
                                jFormattedTextField2.setValue(Math.abs(((Number) jFormattedTextField2.getValue()).doubleValue()));
                        }
                } else if ((JFormattedTextField) evt.getSource() == jFormattedTextField4) {
                        if (((Number) jFormattedTextField4.getValue()).doubleValue() < 0.00) {
                                jFormattedTextField4.setValue(Math.abs(((Number) jFormattedTextField4.getValue()).doubleValue()));
                        }
                }
		*/
		
        }//GEN-LAST:event_jFormattedTextField2debitAndCreditFocusLost

        private void jButton2postButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2postButtonAction
                if (gpAccountField.getSelectedItem() != null) {
                        String accountNumber = "" + gpAccountField.getSelectedItem();
                        accountNumber = accountNumber.substring(0, accountNumber.indexOf("-")).trim();
                        String query = "Insert Into AccountingGLTable "
                        + "(AccountNumber,Debit,Credit,ControlNumber,ReferenceNumber,PostDate,LotName,GLType) "
                        + "Select " + accountNumber + "," + jFormattedTextField2.getText() + "," + jFormattedTextField4.getText() + ","
                        + "'" + jTextField3.getText().replace("'", "''") + "','" + jTextField8.getText().replace("'", "''") + "',"
                        + "'" + AccountingUtil.dateFormat.format(jDateChooser3.getDate()) + "','" + dms.DMSApp.getApplication().getCurrentlotName() + "','General'";
                        sql = new String[1];
                        sql[0] = query;

                        if (dms.DMSApp.getApplication().getDBConnection().executeStatements(sql, this)) {
                                try {
                                        gpAccountField.setSelectedIndex(-1);
                                        jFormattedTextField2.setValue(0.00);
                                        jFormattedTextField4.setValue(0.00);
                                        jTextField3.setText("");
                                        jTextField8.setText("");
                                        //AccountingWindow.reloadLastPosted();
                                } catch (Exception e) {
                                        dms.DMSApp.displayMessage(this, e.getLocalizedMessage(), dms.DMSApp.ERROR_MESSAGE);
                                }
                        }
                }
        }//GEN-LAST:event_jButton2postButtonAction

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.Box.Filler filler3;
        public com.jidesoft.swing.AutoCompletionComboBox gpAccountField;
        private javax.swing.JButton jButton2;
        private com.toedter.calendar.JDateChooser jDateChooser3;
        private javax.swing.JFormattedTextField jFormattedTextField2;
        private javax.swing.JFormattedTextField jFormattedTextField4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel105;
        private javax.swing.JPanel jPanel106;
        private javax.swing.JPanel jPanel91;
        private javax.swing.JScrollPane jScrollPane22;
        private javax.swing.JTabbedPane jTabbedPane1;
        public javax.swing.JTable jTable6;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField8;
        // End of variables declaration//GEN-END:variables
}
