/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dms.panels;

/**
 *
 * @author Lester Ariel Mesa
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Testing
     */
    public SettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        settingsPane = new com.jidesoft.swing.JideTabbedPane();
        jPanel152 = new javax.swing.JPanel();
        jPanel153 = new javax.swing.JPanel();
        jPanel160 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel157 = new javax.swing.JPanel();
        jPanel161 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel158 = new javax.swing.JPanel();
        jPanel162 = new javax.swing.JPanel();
        jPanel163 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jPanel164 = new javax.swing.JPanel();
        jPanel165 = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jPanel151 = new javax.swing.JPanel();
        jPanel166 = new javax.swing.JPanel();
        jPanel167 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane29 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jPanel168 = new javax.swing.JPanel();
        jPanel169 = new javax.swing.JPanel();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        mappingsPane = new com.jidesoft.swing.JideTabbedPane();
        jPanel154 = new javax.swing.JPanel();
        jPanel178 = new javax.swing.JPanel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jPanel180 = new javax.swing.JPanel();
        jPanel176 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jPanel181 = new javax.swing.JPanel();
        jPanel190 = new javax.swing.JPanel();
        jPanel198 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel94 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel97 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jPanel179 = new javax.swing.JPanel();
        jPanel197 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel92 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel93 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel126 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jPanel159 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jComboBox16 = new javax.swing.JComboBox();
        jComboBox17 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();
        jComboBox19 = new javax.swing.JComboBox();
        jComboBox20 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel155 = new javax.swing.JPanel();
        jPanel156 = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        settingsPane.setBoldActiveTab(true);
        settingsPane.setFont(new java.awt.Font("Tahoma 13 12", 0, 12)); // NOI18N
        settingsPane.setName("settingsPane"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dms.DMSApp.class).getContext().getResourceMap(SettingsPanel.class);
        settingsPane.setSelectedTabFont(resourceMap.getFont("settingsPane.selectedTabFont")); // NOI18N

        jPanel152.setName("jPanel152"); // NOI18N
        jPanel152.setOpaque(false);
        jPanel152.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel152ComponentShown(evt);
            }
        });
        jPanel152.setLayout(new java.awt.BorderLayout());

        jPanel153.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel153.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel153.border.titleFont"))); // NOI18N
        jPanel153.setMaximumSize(new java.awt.Dimension(500, 448));
        jPanel153.setMinimumSize(new java.awt.Dimension(500, 448));
        jPanel153.setName("jPanel153"); // NOI18N
        jPanel153.setOpaque(false);
        jPanel153.setPreferredSize(new java.awt.Dimension(500, 448));
        jPanel153.setLayout(new java.awt.BorderLayout());

        jPanel160.setMaximumSize(new java.awt.Dimension(450, 23));
        jPanel160.setMinimumSize(new java.awt.Dimension(450, 23));
        jPanel160.setName("jPanel160"); // NOI18N
        jPanel160.setOpaque(false);
        jPanel160.setPreferredSize(new java.awt.Dimension(450, 23));
        jPanel160.setLayout(new java.awt.GridLayout(1, 0));

        jButton23.setText(resourceMap.getString("jButton23.text")); // NOI18N
        jButton23.setName("jButton23"); // NOI18N
        jPanel160.add(jButton23);

        jButton25.setText(resourceMap.getString("jButton25.text")); // NOI18N
        jButton25.setName("jButton25"); // NOI18N
        jPanel160.add(jButton25);

        jButton26.setText(resourceMap.getString("jButton26.text")); // NOI18N
        jButton26.setMaximumSize(new java.awt.Dimension(51, 23));
        jButton26.setMinimumSize(new java.awt.Dimension(51, 23));
        jButton26.setName("jButton26"); // NOI18N
        jButton26.setPreferredSize(new java.awt.Dimension(51, 23));
        jPanel160.add(jButton26);

        filler7.setName("filler7"); // NOI18N
        jPanel160.add(filler7);

        jPanel153.add(jPanel160, java.awt.BorderLayout.NORTH);

        jScrollPane24.setName("jScrollPane24"); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FS Account", "Description", "Type", "Heading"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setName("jTable4"); // NOI18N
        jTable4.setOpaque(false);
        jScrollPane24.setViewportView(jTable4);

        jPanel153.add(jScrollPane24, java.awt.BorderLayout.CENTER);

        jPanel152.add(jPanel153, java.awt.BorderLayout.WEST);

        jPanel157.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel157.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel157.border.titleFont"))); // NOI18N
        jPanel157.setMinimumSize(new java.awt.Dimension(350, 460));
        jPanel157.setName("jPanel157"); // NOI18N
        jPanel157.setOpaque(false);
        jPanel157.setPreferredSize(new java.awt.Dimension(350, 460));
        jPanel157.setLayout(new java.awt.BorderLayout());

        jPanel161.setMinimumSize(new java.awt.Dimension(0, 23));
        jPanel161.setName("jPanel161"); // NOI18N
        jPanel161.setOpaque(false);
        jPanel161.setPreferredSize(new java.awt.Dimension(350, 23));

        javax.swing.GroupLayout jPanel161Layout = new javax.swing.GroupLayout(jPanel161);
        jPanel161.setLayout(jPanel161Layout);
        jPanel161Layout.setHorizontalGroup(
            jPanel161Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        jPanel161Layout.setVerticalGroup(
            jPanel161Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel157.add(jPanel161, java.awt.BorderLayout.NORTH);

        jScrollPane26.setMinimumSize(new java.awt.Dimension(350, 23));
        jScrollPane26.setName("jScrollPane26"); // NOI18N
        jScrollPane26.setOpaque(false);
        jScrollPane26.setPreferredSize(new java.awt.Dimension(350, 402));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "GL Account", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setMinimumSize(new java.awt.Dimension(350, 64));
        jTable5.setName("jTable5"); // NOI18N
        jTable5.setPreferredSize(new java.awt.Dimension(350, 64));
        jScrollPane26.setViewportView(jTable5);

        jPanel157.add(jScrollPane26, java.awt.BorderLayout.CENTER);

        jPanel152.add(jPanel157, java.awt.BorderLayout.CENTER);

        settingsPane.addTab(resourceMap.getString("jPanel152.TabConstraints.tabTitle"), jPanel152); // NOI18N

        jPanel158.setBackground(resourceMap.getColor("jPanel158.background")); // NOI18N
        jPanel158.setName("jPanel158"); // NOI18N
        jPanel158.setOpaque(false);
        jPanel158.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel158vendorsPanelShown(evt);
            }
        });
        jPanel158.setLayout(new java.awt.BorderLayout());

        jPanel162.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel162.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel162.border.titleFont"))); // NOI18N
        jPanel162.setMaximumSize(new java.awt.Dimension(500, 448));
        jPanel162.setMinimumSize(new java.awt.Dimension(500, 448));
        jPanel162.setName("jPanel162"); // NOI18N
        jPanel162.setOpaque(false);
        jPanel162.setPreferredSize(new java.awt.Dimension(500, 448));
        jPanel162.setLayout(new java.awt.BorderLayout());

        jPanel163.setMaximumSize(new java.awt.Dimension(450, 23));
        jPanel163.setMinimumSize(new java.awt.Dimension(450, 23));
        jPanel163.setName("jPanel163"); // NOI18N
        jPanel163.setOpaque(false);
        jPanel163.setPreferredSize(new java.awt.Dimension(450, 23));
        jPanel163.setLayout(new java.awt.GridLayout(1, 0));

        jButton28.setText(resourceMap.getString("jButton28.text")); // NOI18N
        jButton28.setName("jButton28"); // NOI18N
        jPanel163.add(jButton28);

        jButton29.setText(resourceMap.getString("jButton29.text")); // NOI18N
        jButton29.setName("jButton29"); // NOI18N
        jPanel163.add(jButton29);

        jButton30.setText(resourceMap.getString("jButton30.text")); // NOI18N
        jButton30.setMaximumSize(new java.awt.Dimension(51, 23));
        jButton30.setMinimumSize(new java.awt.Dimension(51, 23));
        jButton30.setName("jButton30"); // NOI18N
        jButton30.setPreferredSize(new java.awt.Dimension(51, 23));
        jPanel163.add(jButton30);

        filler8.setName("filler8"); // NOI18N
        jPanel163.add(filler8);

        jPanel162.add(jPanel163, java.awt.BorderLayout.NORTH);

        jScrollPane27.setName("jScrollPane27"); // NOI18N

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Line Number", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable8.setName("jTable8"); // NOI18N
        jTable8.setOpaque(false);
        jScrollPane27.setViewportView(jTable8);

        jPanel162.add(jScrollPane27, java.awt.BorderLayout.CENTER);

        jPanel158.add(jPanel162, java.awt.BorderLayout.WEST);

        jPanel164.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel164.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel164.border.titleFont"))); // NOI18N
        jPanel164.setMinimumSize(new java.awt.Dimension(350, 460));
        jPanel164.setName("jPanel164"); // NOI18N
        jPanel164.setOpaque(false);
        jPanel164.setPreferredSize(new java.awt.Dimension(350, 460));
        jPanel164.setLayout(new java.awt.BorderLayout());

        jPanel165.setMinimumSize(new java.awt.Dimension(0, 23));
        jPanel165.setName("jPanel165"); // NOI18N
        jPanel165.setOpaque(false);
        jPanel165.setPreferredSize(new java.awt.Dimension(350, 23));

        javax.swing.GroupLayout jPanel165Layout = new javax.swing.GroupLayout(jPanel165);
        jPanel165.setLayout(jPanel165Layout);
        jPanel165Layout.setHorizontalGroup(
            jPanel165Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        jPanel165Layout.setVerticalGroup(
            jPanel165Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel164.add(jPanel165, java.awt.BorderLayout.NORTH);

        jScrollPane28.setMinimumSize(new java.awt.Dimension(350, 23));
        jScrollPane28.setName("jScrollPane28"); // NOI18N
        jScrollPane28.setOpaque(false);
        jScrollPane28.setPreferredSize(new java.awt.Dimension(350, 402));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "GL Account", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable9.setMinimumSize(new java.awt.Dimension(350, 64));
        jTable9.setName("jTable9"); // NOI18N
        jTable9.setPreferredSize(new java.awt.Dimension(350, 64));
        jScrollPane28.setViewportView(jTable9);

        jPanel164.add(jScrollPane28, java.awt.BorderLayout.CENTER);

        jPanel158.add(jPanel164, java.awt.BorderLayout.CENTER);

        settingsPane.addTab(resourceMap.getString("jPanel158.TabConstraints.tabTitle"), jPanel158); // NOI18N

        jPanel151.setName("jPanel151"); // NOI18N
        jPanel151.setOpaque(false);
        jPanel151.setLayout(new java.awt.BorderLayout());

        jPanel166.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel166.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel166.border.titleFont"))); // NOI18N
        jPanel166.setMaximumSize(new java.awt.Dimension(500, 448));
        jPanel166.setMinimumSize(new java.awt.Dimension(500, 448));
        jPanel166.setName("jPanel166"); // NOI18N
        jPanel166.setOpaque(false);
        jPanel166.setPreferredSize(new java.awt.Dimension(500, 448));
        jPanel166.setLayout(new java.awt.BorderLayout());

        jPanel167.setMaximumSize(new java.awt.Dimension(450, 23));
        jPanel167.setMinimumSize(new java.awt.Dimension(450, 23));
        jPanel167.setName("jPanel167"); // NOI18N
        jPanel167.setOpaque(false);
        jPanel167.setPreferredSize(new java.awt.Dimension(450, 23));
        jPanel167.setLayout(new java.awt.GridLayout(1, 0));

        jButton31.setText(resourceMap.getString("jButton31.text")); // NOI18N
        jButton31.setName("jButton31"); // NOI18N
        jPanel167.add(jButton31);

        jButton36.setText(resourceMap.getString("jButton36.text")); // NOI18N
        jButton36.setName("jButton36"); // NOI18N
        jPanel167.add(jButton36);

        jButton37.setText(resourceMap.getString("jButton37.text")); // NOI18N
        jButton37.setMaximumSize(new java.awt.Dimension(51, 23));
        jButton37.setMinimumSize(new java.awt.Dimension(51, 23));
        jButton37.setName("jButton37"); // NOI18N
        jButton37.setPreferredSize(new java.awt.Dimension(51, 23));
        jPanel167.add(jButton37);

        filler9.setName("filler9"); // NOI18N
        jPanel167.add(filler9);

        jPanel166.add(jPanel167, java.awt.BorderLayout.NORTH);

        jScrollPane29.setName("jScrollPane29"); // NOI18N

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Schedule Number", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable10.setName("jTable10"); // NOI18N
        jTable10.setOpaque(false);
        jScrollPane29.setViewportView(jTable10);

        jPanel166.add(jScrollPane29, java.awt.BorderLayout.CENTER);

        jPanel151.add(jPanel166, java.awt.BorderLayout.WEST);

        jPanel168.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel168.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel168.border.titleFont"))); // NOI18N
        jPanel168.setMinimumSize(new java.awt.Dimension(350, 460));
        jPanel168.setName("jPanel168"); // NOI18N
        jPanel168.setOpaque(false);
        jPanel168.setPreferredSize(new java.awt.Dimension(350, 460));
        jPanel168.setLayout(new java.awt.BorderLayout());

        jPanel169.setMinimumSize(new java.awt.Dimension(0, 23));
        jPanel169.setName("jPanel169"); // NOI18N
        jPanel169.setOpaque(false);
        jPanel169.setPreferredSize(new java.awt.Dimension(350, 23));

        javax.swing.GroupLayout jPanel169Layout = new javax.swing.GroupLayout(jPanel169);
        jPanel169.setLayout(jPanel169Layout);
        jPanel169Layout.setHorizontalGroup(
            jPanel169Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        jPanel169Layout.setVerticalGroup(
            jPanel169Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel168.add(jPanel169, java.awt.BorderLayout.NORTH);

        jScrollPane30.setMinimumSize(new java.awt.Dimension(350, 23));
        jScrollPane30.setName("jScrollPane30"); // NOI18N
        jScrollPane30.setOpaque(false);
        jScrollPane30.setPreferredSize(new java.awt.Dimension(350, 402));

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "GL Account", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable11.setMinimumSize(new java.awt.Dimension(350, 64));
        jTable11.setName("jTable11"); // NOI18N
        jTable11.setPreferredSize(new java.awt.Dimension(350, 64));
        jScrollPane30.setViewportView(jTable11);

        jPanel168.add(jScrollPane30, java.awt.BorderLayout.CENTER);

        jPanel151.add(jPanel168, java.awt.BorderLayout.CENTER);

        settingsPane.addTab(resourceMap.getString("jPanel151.TabConstraints.tabTitle"), jPanel151); // NOI18N

        mappingsPane.setBoldActiveTab(true);
        mappingsPane.setFont(resourceMap.getFont("mappingsPane.font")); // NOI18N
        mappingsPane.setName("mappingsPane"); // NOI18N
        mappingsPane.setSelectedTabFont(resourceMap.getFont("mappingsPane.selectedTabFont")); // NOI18N

        jPanel154.setMaximumSize(new java.awt.Dimension(850, 600));
        jPanel154.setMinimumSize(new java.awt.Dimension(850, 600));
        jPanel154.setName("jPanel154"); // NOI18N
        jPanel154.setOpaque(false);
        jPanel154.setPreferredSize(new java.awt.Dimension(850, 600));
        jPanel154.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel154ComponentShown(evt);
            }
        });
        jPanel154.setLayout(new java.awt.BorderLayout());

        jPanel178.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel178.setMinimumSize(new java.awt.Dimension(958, 30));
        jPanel178.setName("jPanel178"); // NOI18N
        jPanel178.setOpaque(false);
        jPanel178.setPreferredSize(new java.awt.Dimension(958, 30));
        jPanel178.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setSelected(true);
        jRadioButton11.setText(resourceMap.getString("jRadioButton11.text")); // NOI18N
        jRadioButton11.setName("jRadioButton11"); // NOI18N
        jRadioButton11.setOpaque(false);
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel178.add(jRadioButton11);

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText(resourceMap.getString("jRadioButton12.text")); // NOI18N
        jRadioButton12.setName("jRadioButton12"); // NOI18N
        jRadioButton12.setOpaque(false);
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel178.add(jRadioButton12);

        jPanel154.add(jPanel178, java.awt.BorderLayout.NORTH);

        jPanel180.setName("jPanel180"); // NOI18N
        jPanel180.setLayout(new java.awt.BorderLayout());

        jPanel176.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel176.setMinimumSize(new java.awt.Dimension(125, 605));
        jPanel176.setName("jPanel176"); // NOI18N
        jPanel176.setOpaque(false);
        jPanel176.setPreferredSize(new java.awt.Dimension(125, 605));

        jButton38.setText(resourceMap.getString("jButton38.text")); // NOI18N
        jButton38.setMaximumSize(new java.awt.Dimension(105, 23));
        jButton38.setMinimumSize(new java.awt.Dimension(105, 23));
        jButton38.setName("jButton38"); // NOI18N
        jButton38.setPreferredSize(new java.awt.Dimension(105, 23));
        jPanel176.add(jButton38);

        jButton39.setText(resourceMap.getString("jButton39.text")); // NOI18N
        jButton39.setName("jButton39"); // NOI18N
        jPanel176.add(jButton39);

        jButton40.setText(resourceMap.getString("jButton40.text")); // NOI18N
        jButton40.setMaximumSize(new java.awt.Dimension(105, 23));
        jButton40.setMinimumSize(new java.awt.Dimension(105, 23));
        jButton40.setName("jButton40"); // NOI18N
        jButton40.setPreferredSize(new java.awt.Dimension(105, 23));
        jPanel176.add(jButton40);

        jButton41.setText(resourceMap.getString("jButton41.text")); // NOI18N
        jButton41.setMaximumSize(new java.awt.Dimension(105, 23));
        jButton41.setMinimumSize(new java.awt.Dimension(105, 23));
        jButton41.setName("jButton41"); // NOI18N
        jButton41.setPreferredSize(new java.awt.Dimension(105, 23));
        jPanel176.add(jButton41);

        jPanel180.add(jPanel176, java.awt.BorderLayout.WEST);

        jPanel181.setName("jPanel181"); // NOI18N
        jPanel181.setLayout(new java.awt.CardLayout());

        jPanel190.setName("jPanel190"); // NOI18N

        jPanel198.setName("jPanel198"); // NOI18N
        jPanel198.setLayout(new java.awt.GridBagLayout());

        jCheckBox8.setName("jCheckBox8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel198.add(jCheckBox8, gridBagConstraints);

        jLabel94.setFont(resourceMap.getFont("jLabel94.font")); // NOI18N
        jLabel94.setText(resourceMap.getString("jLabel94.text")); // NOI18N
        jLabel94.setName("jLabel94"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel198.add(jLabel94, gridBagConstraints);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setName("jComboBox6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel198.add(jComboBox6, gridBagConstraints);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setName("jComboBox7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel198.add(jComboBox7, gridBagConstraints);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.setName("jComboBox8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel198.add(jComboBox8, gridBagConstraints);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox9.setName("jComboBox9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel198.add(jComboBox9, gridBagConstraints);

        jLabel97.setFont(resourceMap.getFont("jLabel97.font")); // NOI18N
        jLabel97.setText(resourceMap.getString("jLabel97.text")); // NOI18N
        jLabel97.setName("jLabel97"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel198.add(jLabel97, gridBagConstraints);

        jLabel108.setFont(resourceMap.getFont("jLabel108.font")); // NOI18N
        jLabel108.setText(resourceMap.getString("jLabel108.text")); // NOI18N
        jLabel108.setName("jLabel108"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel198.add(jLabel108, gridBagConstraints);

        jLabel118.setFont(resourceMap.getFont("jLabel118.font")); // NOI18N
        jLabel118.setText(resourceMap.getString("jLabel118.text")); // NOI18N
        jLabel118.setName("jLabel118"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel198.add(jLabel118, gridBagConstraints);

        jLabel119.setFont(resourceMap.getFont("jLabel119.font")); // NOI18N
        jLabel119.setText(resourceMap.getString("jLabel119.text")); // NOI18N
        jLabel119.setName("jLabel119"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel198.add(jLabel119, gridBagConstraints);

        jLabel125.setText(resourceMap.getString("jLabel125.text")); // NOI18N
        jLabel125.setName("jLabel125"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel198.add(jLabel125, gridBagConstraints);

        javax.swing.GroupLayout jPanel190Layout = new javax.swing.GroupLayout(jPanel190);
        jPanel190.setLayout(jPanel190Layout);
        jPanel190Layout.setHorizontalGroup(
            jPanel190Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel190Layout.createSequentialGroup()
                .addComponent(jPanel198, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel190Layout.setVerticalGroup(
            jPanel190Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel190Layout.createSequentialGroup()
                .addComponent(jPanel198, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 483, Short.MAX_VALUE))
        );

        jPanel181.add(jPanel190, "card3");

        jPanel179.setName("jPanel179"); // NOI18N

        jPanel197.setName("jPanel197"); // NOI18N
        jPanel197.setLayout(new java.awt.GridBagLayout());

        jCheckBox7.setName("jCheckBox7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel197.add(jCheckBox7, gridBagConstraints);

        jLabel92.setFont(resourceMap.getFont("jLabel92.font")); // NOI18N
        jLabel92.setText(resourceMap.getString("jLabel92.text")); // NOI18N
        jLabel92.setName("jLabel92"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel197.add(jLabel92, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setName("jComboBox2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox2, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox3, gridBagConstraints);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setName("jComboBox4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox4, gridBagConstraints);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setName("jComboBox5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox5, gridBagConstraints);

        jLabel93.setFont(resourceMap.getFont("jLabel93.font")); // NOI18N
        jLabel93.setText(resourceMap.getString("jLabel93.text")); // NOI18N
        jLabel93.setName("jLabel93"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel197.add(jLabel93, gridBagConstraints);

        jLabel105.setFont(resourceMap.getFont("jLabel105.font")); // NOI18N
        jLabel105.setText(resourceMap.getString("jLabel105.text")); // NOI18N
        jLabel105.setName("jLabel105"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel197.add(jLabel105, gridBagConstraints);

        jLabel115.setFont(resourceMap.getFont("jLabel115.font")); // NOI18N
        jLabel115.setText(resourceMap.getString("jLabel115.text")); // NOI18N
        jLabel115.setName("jLabel115"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel197.add(jLabel115, gridBagConstraints);

        jLabel116.setFont(resourceMap.getFont("jLabel116.font")); // NOI18N
        jLabel116.setText(resourceMap.getString("jLabel116.text")); // NOI18N
        jLabel116.setName("jLabel116"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel197.add(jLabel116, gridBagConstraints);

        jLabel124.setText(resourceMap.getString("jLabel124.text")); // NOI18N
        jLabel124.setName("jLabel124"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jLabel124, gridBagConstraints);

        jCheckBox9.setName("jCheckBox9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel197.add(jCheckBox9, gridBagConstraints);

        jLabel126.setText(resourceMap.getString("jLabel126.text")); // NOI18N
        jLabel126.setName("jLabel126"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jLabel126, gridBagConstraints);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox10.setName("jComboBox10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox10, gridBagConstraints);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox11.setName("jComboBox11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox11, gridBagConstraints);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox12.setName("jComboBox12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox12, gridBagConstraints);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox13.setName("jComboBox13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel197.add(jComboBox13, gridBagConstraints);

        javax.swing.GroupLayout jPanel179Layout = new javax.swing.GroupLayout(jPanel179);
        jPanel179.setLayout(jPanel179Layout);
        jPanel179Layout.setHorizontalGroup(
            jPanel179Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel179Layout.createSequentialGroup()
                .addComponent(jPanel197, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel179Layout.setVerticalGroup(
            jPanel179Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel179Layout.createSequentialGroup()
                .addComponent(jPanel197, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 483, Short.MAX_VALUE))
        );

        jPanel181.add(jPanel179, "card3");

        jPanel180.add(jPanel181, java.awt.BorderLayout.CENTER);

        jPanel154.add(jPanel180, java.awt.BorderLayout.CENTER);

        mappingsPane.addTab(resourceMap.getString("jPanel154.TabConstraints.tabTitle"), jPanel154); // NOI18N

        jPanel159.setBackground(resourceMap.getColor("jPanel159.background")); // NOI18N
        jPanel159.setName("jPanel159"); // NOI18N
        jPanel159.setOpaque(false);
        jPanel159.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel159vendorsPanelShown(evt);
            }
        });
        jPanel159.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel8, gridBagConstraints);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox14.setName("jComboBox14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox14, gridBagConstraints);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox15.setName("jComboBox15"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox15, gridBagConstraints);

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox16.setName("jComboBox16"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox16, gridBagConstraints);

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox17.setName("jComboBox17"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox17, gridBagConstraints);

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox18.setName("jComboBox18"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox18, gridBagConstraints);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox19.setName("jComboBox19"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox19, gridBagConstraints);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox20.setName("jComboBox20"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jComboBox20, gridBagConstraints);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel12, gridBagConstraints);

        jPanel159.add(jPanel1);

        mappingsPane.addTab(resourceMap.getString("jPanel159.TabConstraints.tabTitle"), jPanel159); // NOI18N

        jPanel155.setName("jPanel155"); // NOI18N
        jPanel155.setOpaque(false);

        javax.swing.GroupLayout jPanel155Layout = new javax.swing.GroupLayout(jPanel155);
        jPanel155.setLayout(jPanel155Layout);
        jPanel155Layout.setHorizontalGroup(
            jPanel155Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel155Layout.setVerticalGroup(
            jPanel155Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mappingsPane.addTab(resourceMap.getString("jPanel155.TabConstraints.tabTitle"), jPanel155); // NOI18N

        jPanel156.setName("jPanel156"); // NOI18N
        jPanel156.setOpaque(false);

        javax.swing.GroupLayout jPanel156Layout = new javax.swing.GroupLayout(jPanel156);
        jPanel156.setLayout(jPanel156Layout);
        jPanel156Layout.setHorizontalGroup(
            jPanel156Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel156Layout.setVerticalGroup(
            jPanel156Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mappingsPane.addTab(resourceMap.getString("jPanel156.TabConstraints.tabTitle"), jPanel156); // NOI18N

        settingsPane.addTab(resourceMap.getString("mappingsPane.TabConstraints.tabTitle"), mappingsPane); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(settingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(settingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel152ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel152ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel152ComponentShown

    private void jPanel158vendorsPanelShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel158vendorsPanelShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel158vendorsPanelShown

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        jPanel179.setVisible(true);
        jPanel190.setVisible(false);
        // vendorsTable.setEnabled(jRadioButton11.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jPanel154ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel154ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel154ComponentShown

    private void jPanel159vendorsPanelShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel159vendorsPanelShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel159vendorsPanelShown

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        jPanel179.setVisible(false);
        jPanel190.setVisible(true);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel151;
    private javax.swing.JPanel jPanel152;
    private javax.swing.JPanel jPanel153;
    private javax.swing.JPanel jPanel154;
    private javax.swing.JPanel jPanel155;
    private javax.swing.JPanel jPanel156;
    private javax.swing.JPanel jPanel157;
    private javax.swing.JPanel jPanel158;
    private javax.swing.JPanel jPanel159;
    private javax.swing.JPanel jPanel160;
    private javax.swing.JPanel jPanel161;
    private javax.swing.JPanel jPanel162;
    private javax.swing.JPanel jPanel163;
    private javax.swing.JPanel jPanel164;
    private javax.swing.JPanel jPanel165;
    private javax.swing.JPanel jPanel166;
    private javax.swing.JPanel jPanel167;
    private javax.swing.JPanel jPanel168;
    private javax.swing.JPanel jPanel169;
    private javax.swing.JPanel jPanel176;
    private javax.swing.JPanel jPanel178;
    private javax.swing.JPanel jPanel179;
    private javax.swing.JPanel jPanel180;
    private javax.swing.JPanel jPanel181;
    private javax.swing.JPanel jPanel190;
    private javax.swing.JPanel jPanel197;
    private javax.swing.JPanel jPanel198;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private com.jidesoft.swing.JideTabbedPane mappingsPane;
    private com.jidesoft.swing.JideTabbedPane settingsPane;
    // End of variables declaration//GEN-END:variables
}
